//------------------------------------------------------------------------
// Copyright(c) 2023 Musiola.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Musynth.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Musynth VST3 (64Bit)"
#else
#define stringFileDescription	"Musynth VST3"
#endif
#define stringCompanyName		"Musiola\0"
#define stringLegalCopyright	"Copyright(c) 2023 Musiola."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
